---
- name: Install pre-requisites
  apt:
    package:
      - build-essential
      - git
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - liblzma-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
  become_user: root

- name: Install pyenv
  shell: >
    set -o pipetail && \
    curl https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.PWD }}/.pyenv"

- name: Set up pyenv
  lineinfile:
    dest: "{{ ansible_env.PWD }}/.bashrc"
    line: "{{ item }}"
    backup: yes
  with_items:
    - 'export PATH="$HOME/.pyenv/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'
