---
- name: Install pre-requisites
  apt:
    package:
      - build-essential
      - git
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - liblzma-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
  become_user: root

- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    version: "{{ pyenv_version }}"
    dest: "{{ pyenv_home }}"
    recursive: true

- name: Set up pyenv
  lineinfile:
    dest: "{{ ansible_env.PWD }}/.bashrc"
    line: "{{ item }}"
    backup: yes
  with_items:
    - 'export PYENV_ROOT="{{ pyenv_home }}"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: Install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    version: "{{ pyenv_virtualenv_version }}"
    dest: "{{ pyenv_home }}/plugins/pyenv-virtualenv"
    recursive: true

- name: Set up pyenv-virtualenv
  lineinfile:
    dest: "{{ ansible_env.PWD }}/.bashrc"
    line: 'eval "$(pyenv virtualenv-init -)"'
    backup: yes
