---
- name: Install pre-requisites
  apt:
    name: "{{ item }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add GPG key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: 0EBFCD88

- name: Add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu/ {{ ansible_lsb.codename }} stable'
  register: result

- name: Update repositories cache
  apt:
    update_cache: true
  when: result.changed

- name: Install Docker
  apt:
    name: docker-ce

- name: Add users to docker group
  user:
    user: '{{ item }}'
    groups:
      - docker
  with_items: '{{ docker_users }}'
