---
- name: Install pre-requisites
  apt:
    package:
      - build-essential
      - 'linux-headers-{{ ansible_kernel }}'

- name: Add CUDA repository
  apt:
    deb: "{{ cuda_repo_deb[cuda_version] }}"
  ignore_errors: true

- name: Add GPG key
  apt_key:
    id: 7FA2AF80
    url: '{{ cuda_repo_base_url }}/7fa2af80.pub'

- name: Add machine learning repository
  apt:
    deb: '{{ cuda_ml_repo_deb }}'

- name: Install CUDA drivers
  apt:
    update_cache: true
    name: cuda-drivers
  when: cuda_drivers_only
  register: result_install_drivers

- name: Install CUDA
  apt:
    package:
      - "cuda-{{ cuda_version | replace('.', '-') }}"
  when: not cuda_drivers_only
  register: result_install_cuda

- name: Get cuDNN package name
  shell: >
    set -o pipefail && \
    apt-cache policy libcudnn7 | grep "{{ cuda_cudnn_version }}.*{{ cuda_version }}" | head -n -1 | awk '{$1=$1}1' | cut -d ' ' -f 1
  register: result_get_cudnn_package_name

- name: Install cuDNN
  apt:
    package:
      - "libcudnn7={{ result_get_cudnn_package_name.stdout }}"
      - "libcudnn7-dev={{ result_get_cudnn_package_name.stdout }}"
    update_cache: yes

- name: Restart machine
  shell: sleep 2 && /sbin/shutdown -r now 'Reboot triggered by Ansible'
  args:
    removes: /var/run/reboot-required
  async: 1
  poll: 0
  when: result_install_drivers.changed or result_install_cuda.changed
  notify:
    - 'Wait for machine to come back'

- meta: flush_handlers
