---
- name: Install pre-requisites
  apt:
    package:
      - build-essential
      - 'linux-headers-{{ ansible_kernel }}'

- name: Install repository meta data
  apt:
    deb: "{{ cuda_repo_metadata[cuda_version] }}"
  ignore_errors: true

- name: Add GPG key
  apt_key:
    id: 7FA2AF80
    url: 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub'

- name: Add machine learning repository
  apt:
    deb: 'http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb'
    update_cache: yes

- name: Install CUDA drivers
  apt:
    update_cache: true
    name: cuda-drivers
  when: cuda_drivers_only
  register: result_install_drivers

- name: Install CUDA
  apt:
    package:
      - "cuda-{{ cuda_version | replace('.', '-') }}"
      - libcudnn7
  when: not cuda_drivers_only
  register: result_install_cuda

- name: Restart machine
  shell: sleep 2 && /sbin/shutdown -r now 'Reboot triggered by Ansible'
  args:
    removes: /var/run/reboot-required
  async: 1
  poll: 0
  when: result_install_drivers.changed or result_install_cuda.changed
  notify:
    - 'Wait for machine to come back'

- meta: flush_handlers
