---
- name: Download installer
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /var/tmp/Miniconda3-latest-Linux-x86_64.sh
    force: no

- name: Install conda
  command: bash Miniconda3-latest-Linux-x86_64.sh -b -p "{{ conda_home }}"
  args:
    chdir: /var/tmp
    creates: "{{ conda_home }}"

- name: Set up conda
  lineinfile:
    dest: "{{ ansible_env.PWD }}/.bashrc"
    line: '. "{{ conda_home }}/etc/profile.d/conda.sh"'
    backup: yes
