---
- name: Install pre-requisites
  apt:
    package:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add GPG key
  apt_key:
    url: 'https://nvidia.github.io/nvidia-docker/gpgkey'

- name: Add repository
  get_url:
    url: 'https://nvidia.github.io/nvidia-docker/{{ _docker_ubuntu_version_str }}/amd64/nvidia-docker.list'
    dest: '/etc/apt/sources.list.d/nvidia-docker.list'
  register: result

- name: Install nvidia-docker
  apt:
    update_cache: true
    package:
      - nvidia-container-toolkit
  register: result

- name: Reload Docker daemon configuration
  command: systemctl restart docker
  when: result.changed
